In [2]:
import pandas as pd

In [5]:
data = pd.read_csv('./Datos_VuelaAlpes.csv')

## 2. Exploración de los datos


* Completitud.
* Unicidad.
* Consistencia.
* Validez.

### Completitud

In [6]:
((data.isnull().sum()/data.shape[0])).sort_values(ascending=False)

Arrival Delay in Minutes             0.0025
Gender                               0.0000
id                                   0.0000
Age                                  0.0000
Type of Travel                       0.0000
Class                                0.0000
Customer Type                        0.0000
Flight Distance                      0.0000
Inflight wifi service                0.0000
Ease of Online booking               0.0000
Departure/Arrival time convenient    0.0000
Food and drink                       0.0000
Online boarding                      0.0000
Seat comfort                         0.0000
Gate location                        0.0000
Inflight entertainment               0.0000
On-board service                     0.0000
Baggage handling                     0.0000
Leg room service                     0.0000
Checkin service                      0.0000
Inflight service                     0.0000
Cleanliness                          0.0000
Departure Delay in Minutes           0.0000
dtype: float64

Registros con valores nulos

In [7]:
# Filtrar filas
nulos = data[data['Arrival Delay in Minutes'].isna()].copy()

# Contar cuántas son
print(f"Filas con 'Arrival Delay in Minutes' nula: {nulos.shape[0]}")

# Guardar los índices
indices = data.index[data['Arrival Delay in Minutes'].isna()]

# Mostrar tabla
nulos

Filas con 'Arrival Delay in Minutes' nula: 25

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
242,45562,Female,Loyal Customer,49,Business travel,Business,2266,4,3,4,...,5,4,4,4,4,1,4,1,28,NaN
1029,121173,Female,Loyal Customer,28,Personal Travel,Eco,2370,4,5,4,...,3,3,5,4,4,5,4,3,3,NaN
1044,48435,Female,Loyal Customer,26,Business travel,Business,2351,1,1,5,...,4,4,1,1,4,3,4,4,30,NaN
1230,18169,Female,Loyal Customer,45,Business travel,Business,2236,2,1,1,...,3,2,2,2,2,2,2,2,84,NaN
1640,11845,Female,Loyal Customer,31,Business travel,Business,3037,1,1,3,...,2,2,3,4,4,4,4,2,127,NaN
1993,67632,Female,Loyal Customer,25,Business travel,Business,1723,2,2,2,...,4,4,5,4,4,4,5,4,2,NaN
2412,50179,Female,Loyal Customer,39,Business travel,Eco,89,5,4,4,...,5,5,4,4,5,3,4,5,0,NaN
2816,89345,Male,Loyal Customer,26,Business travel,Business,1541,2,4,4,...,2,2,3,4,4,3,3,2,1,NaN
3167,46936,Female,disloyal Customer,63,Personal Travel,Eco,776,5,5,4,...,3,3,5,2,5,3,5,3,7,NaN
3774,19620,Male,disloyal Customer,24,Business travel,Eco,416,3,0,3,...,4,4,2,4,3,5,2,4,89,NaN
3809,41160,Female,Loyal Customer,9,Personal Travel,Eco,295,1,5,4,...,1,1,4,5,5,5,2,1,16,NaN
4140,92980,Male,Loyal Customer,46,Business travel,Business,738,4,4,4,...,5,5,5,5,5,3,5,4,21,NaN
4220,67562,Female,Loyal Customer,46,Business travel,Business,2860,3,3,3,...,5,5,5,5,5,4,5,5,2,NaN
4394,106599,Female,Loyal Customer,60,Business travel,Business,2446,3,3,5,...,5,4,4,4,4,3,4,3,0,NaN
4564,19598,Male,Loyal Customer,51,Personal Travel,Eco,160,1,5,1,...,4,4,3,4,5,4,5,4,0,NaN
4582,116374,Female,Loyal Customer,24,Personal Travel,Eco,417,2,1,2,...,5,5,1,4,2,1,2,5,1,NaN
5732,114134,Female,Loyal Customer,33,Business travel,Business,3546,4,4,4,...,4,5,5,5,5,5,5,4,3,NaN
6006,17633,Male,Loyal Customer,21,Personal Travel,Eco,980,3,4,3,...,2,2,3,3,3,2,2,2,190,NaN
7680,105399,Male,Loyal Customer,60,Personal Travel,Eco,369,2,1,4,...,3,3,2,4,2,3,3,3,10,NaN
8122,11785,Male,Loyal Customer,63,Personal Travel,Eco,429,1,4,5,...,2,2,4,4,1,2,5,2,15,NaN
9248,99849,Female,Loyal Customer,26,Personal Travel,Eco,587,3,4,4,...,2,2,5,3,5,5,5,2,66,NaN
9370,26055,Male,Loyal Customer,11,Personal Travel,Eco,432,2,4,2,...,1,1,4,2,5,3,4,1,98,NaN
9670,41378,Male,Loyal Customer,9,Business travel,Business,2681,2,3,4,...,2,2,3,5,3,3,4,2,0,NaN
9739,59030,Female,disloyal Customer,21,Business travel,Eco,1846,2,2,2,...,2,5,4,2,3,3,4,5,0,NaN
9982,21812,Male,Loyal Customer,53,Personal Travel,Eco,352,4,5,4,...,1,1,4,2,4,4,4,1,30,NaN

¿25 faltantes es mucho o poco?

In [8]:
(25 / len(data)) * 100

0.25

Solo el 0.25% del dataset tiene valores faltantes. La imputación contextualizada resulta adecuada debido a la relación operacional existente entre el retraso de salida y el retraso de llegada. Desde el dominio del problema, un vuelo que despega con retraso tiende también a llegar tarde, por lo que ambas variables presentan dependencia estadística y coherencia operacional. Utilizar esta relación permite preservar mejor la estructura del dataset y reducir el sesgo introducido por imputaciones simples basadas únicamente en medidas de tendencia central.

In [9]:
# Revisar correlación
data[['Departure Delay in Minutes',
         'Arrival Delay in Minutes']].corr()

,Departure Delay in Minutes,Arrival Delay in Minutes
Departure Delay in Minutes,1.000000,0.962373
Arrival Delay in Minutes,0.962373,1.000000

Casi dependencia lineal directa